### ISSUE TITLE
missing gnome-shell 

### ISSUE THREAD

**Issue by shmsh9** [B00merang-Project/macOS-Sierra-Dark#1]
all is in the title

**Comment by Elbullazul** [comment]
@shmsh9 will update soon

**Comment by bluedxca93** [comment]
@shmsh9 can you write which version of gnome-shell. i bet 3.18 and
3.20 is very different.

its similar to cinnamon theming.

**Comment by shmsh9** [comment]
3.18.2 indeed but white version is working like a charm

**Comment by Elbullazul** [comment]
@shmsh9 I have pushed a VERY basic dark theme for shell, expect some updates on it soon
