### ISSUE TITLE
checkbox is not properly shown

### ISSUE THREAD

**Issue by handrake0724** [B00merang-Project/macOS-Sierra-Dark#2]
Below image is from dia.
There is a checkbox next to Template class. I guess the marker should be blue or something visible but it is not recognizable. Same behavior is shown in macOS-Sierra.

![screenshot from 2017-05-29 23-38-15](https://cloud.githubusercontent.com/assets/18005991/26553793/2ab643b8-44c8-11e7-8187-d65d0a7e944e.png)

**Comment by Elbullazul** [comment]
@handrake0724 that's a GTK2 app, right?

Seems like murrine is getting less and less supported, so maybe I'll have to adapt the theme to Pixbuf

**Comment by handrake0724** [comment]
Yes, dia is a GTK2 app. could it be fixed?

**Comment by Elbullazul** [comment]
yes, but will take some time...

**Comment by Elbullazul** [comment]
@handrake0724 does the latest master fix the issue?

**Comment by Elbullazul** [comment]
@handrake0724 is it fixed?

**Comment by handrake0724** [comment]
Yes, it is now working perfectly.
Thanks.
