### ISSUE TITLE
remove the "glow" from the shell

### ISSUE THREAD

**Issue by cajuuh** [B00merang-Project/macOS-Sierra-Dark#3]
is there a way to remove the "glowing" effect on the shell icons, the "clear all" button almost made me blind.

**Comment by Elbullazul** [comment]
Can you post a screenshot of the issue please?

**Comment by cajuuh** [comment]
> Can you post a screenshot of the issue please?

![novo](https://user-images.githubusercontent.com/806660/32451483-a9bb4c20-c2f5-11e7-8745-e55be087d3da.png)

see? that glow effect on the icons?

**Comment by Elbullazul** [comment]
should be fixed
